## ~/.config/i3/dark.conf - Feb 12 2023, sav@alekhine -*- mode: i3wm-config; eval: (rainbow-mode); -*-

# class                 border  bground text    indicator child_border
client.focused          #101887 #122039 #ffffff #b3d3f4   #101870
client.focused_inactive #333333 #161c27 #7e838f #484e50   #010843
client.unfocused        #202020 #080925 #585e60 #292D2e   #000030
client.urgent           #000000 #c95243 #ffffff #ffcd17   #f48d3e
client.placeholder      #000000 #0c0c0c #ffffff #000000   #3fcd17
client.background       #000000 #0c0c0c #ffffff #000000   #0c0c0c

bar {
    status_command          i3status -c ~/.config/i3/status-dark.conf
    font                    pango:Sans 9
    position                bottom
    binding_mode_indicator  yes
    strip_workspace_numbers no
    workspace_buttons       yes
    tray_padding            4
    mode                    dock
    hidden_state            hide
    modifier                none
    separator_symbol        “⁞”

    colors {
      background         #122039
      statusline         #e8e8e8
      separator          #010843

      focused_workspace  #aBc6f9 #101877 #f0f0f0
      active_workspace   #333333 #222222 #FFFFFF
      inactive_workspace #333333 #000000 #707092
      urgent_workspace   #2F343A #C95243 #FFFFFF
      binding_mode       #2F343A #C95243 #FFFFFF
    }
}
# vim:noet:tw=108:ts=4:ft=conf:norl:
