## ~/.config/i3/light.conf - Feb 12 2023, sav@alekhine -*- mode: i3wm-config; eval: (rainbow-mode); -*-

## class                border  bground text    indicator child_border
client.focused          #b8c5db #445ba7 #ffffff #010843 #445ba7
client.focused_inactive #b8c5db #dadce3 #37474f #4271AE #dee6f7
client.unfocused        #202020 #e2e2ee #a1a1a1 #292D2e #dee6f7
client.urgent           #000000 #445ba7 #000000 #17cdff #dee6f7
client.placeholder      #000000 #ffab91 #17cdff #000000 #dee6f7
client.background       #000000 #ffab91 #17ccfe #000000 #dee6f7

bar {
    status_command          i3status -c ~/.config/i3/status-light.conf
    font                    pango:Sans Bold 9
    position                bottom
    binding_mode_indicator  yes
    strip_workspace_numbers no
    workspace_buttons       yes
    tray_padding            1
    mode                    dock
    hidden_state            hide
    separator_symbol        “⁞”
    modifier                none

    colors {
        background              #ffffff
        statusline              #000000
        separator               #000000
    
        focused_workspace       #606090 #445ba7 #e2e2ff
        active_workspace        #445ba7 #9c9cef #e2e2ff
        inactive_workspace      #a2a2ff #eef3fc #626292
        urgent_workspace        #4B36a9 #4290f5 #000000
        binding_mode            #4B36a9 #4290f5 #000000
    }
}

# vim:noet:tw=108:ts=4:ft=conf:norl:
