# ~/.config/i3/status-light.conf - i3status configuration file. -*- eval: (rainbow-mode); -*-

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        output_format  = i3bar
        colors         = true
        interval       = 16
        colors         = true
        color_good     = "#150e5c"
        color_degraded = "#5c550e"
        color_bad      = "#5c150e"
}

order += "load"
order += "ethernet eth0"
order += "memory"
order += "tztime local"

wireless wlo1 {
        format_up = "  %essid (%quality)    🖧 %ip"
        format_down = "  eth"
        align = "left"
        separator = false
        separator_block_width = 2
}

ethernet eth0 {
        format_up = "🖧 %ip (%speed)"
        format_down = " eth"
}

battery all {
        format = "%status %percentage  ⁞   %remaining   [%emptytime]  ⁞  "
        format_down = "No battery"
        status_chr = "⚡"
        status_bat = "🔋"
        status_unk = "?"
        status_full = "😎"
        path = "/sys/class/power_supply/BAT%d/uevent"
        last_full_capacity = true
        threshold_type=percentage
        low_threshold=10
        align="right"
        separator=false
}

disk "/home" {
        format = "🏠  free: %avail"
}

load {
        format = "💻  %5min  %15min"
        align = "center"
        separator = true
}

cpu_temperature 0 {
        format = "🌡 %degrees °C"
        path = "/sys/devices/platform/coretemp.0/hwmon/hwmon*/temp1_input"
        align = "center"
        max_threshold = 72
}

memory {
        format = "%used ⁞ %available"
        threshold_degraded = "1G"
        format_degraded = "MEMORY < %available"
}

tztime local {
       format = "   ⁞     📅  %a   %b/%d     ⁞    ⏰  %Hh  %Mm     ⁞   "
       separator = false
       align = "center"
       separator_block_width = 2
}

read_file uptime {
        path = "/proc/uptime"
}
